import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Player} from '@remotion/player';
import {Film,durationFrames} from './film';
import './fonts.css';
import './studio.css';

async function api(url,method='GET',data){
  const response=await fetch('/api/motion'+url,{method,headers:data instanceof FormData?{}:{'Content-Type':'application/json'},body:data?data instanceof FormData?data:JSON.stringify(data):undefined});
  const result=await response.json(); if(!response.ok)throw new Error(result.error||'Permintaan gagal'); return result;
}
const names={title:'Opening title',annotated:'Annotated image',parallax:'Layered image',cutaway:'Geological cutaway',flow:'Flow & particles',comparison:'Comparison',timeline:'Timeline / steps',summary:'Closing summary'};

function App(){
 const [catalog,setCatalog]=useState({topics:[],components:[],styles:[]}),[jobs,setJobs]=useState([]),[assets,setAssets]=useState([]);
 const [job,setJob]=useState(null),[manifest,setManifest]=useState(null),[prepared,setPrepared]=useState(null),[sceneIndex,setSceneIndex]=useState(0);
 const [topic,setTopic]=useState(''),[query,setQuery]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [note,setNote]=useState(''),[ready,setReady]=useState({}),[voice,setVoice]=useState('Kore'),[revisions,setRevisions]=useState([]),[review,setReview]=useState(false);
 const player=useRef(null), latest=useRef({job:null,dirty:false});
 latest.current={job,dirty};
 const loadCounter=useRef(0);
 const load=async(id,background=false)=>{const serial=++loadCounter.current;const b=await api('/jobs/'+id);const history=await api('/jobs/'+id+'/revisions');if(serial!==loadCounter.current||(background&&(latest.current.job?.id!==id||latest.current.dirty)))return;setJob(b.job);setManifest(b.manifest);setPrepared(b.preview);setDirty(false);if(!background)setSceneIndex(0);setRevisions(history.revisions);};
 const refresh=async()=>{const j=await api('/jobs');setJobs(j.jobs);return j.jobs;};
 const act=async(fn)=>{setBusy(true);setError('');setNote('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{act(async()=>{setCatalog(await api('/catalog'));setReady(await api('/readiness'));setAssets((await api('/assets')).assets);await refresh();});},[]);
 useEffect(()=>{let live=true;const timer=setInterval(async()=>{try{const list=await api('/jobs');if(!live)return;setJobs(list.jobs);const current=latest.current.job;if(current){const updated=list.jobs.find(j=>j.id===current.id);if(updated){if(['queued','rendering'].includes(current.status)&&!['queued','rendering'].includes(updated.status)&&!latest.current.dirty){await load(current.id,true);setAssets((await api('/assets')).assets);}else setJob(j=>j?.id===updated.id?updated:j);}}}catch(e){if(live)setError(e.message);}},4000);return()=>{live=false;clearInterval(timer);};},[]);
 const active=job&&['queued','rendering'].includes(job.status), locked=busy||active;
 const edit=(key,value)=>{setManifest(m=>({...m,[key]:value}));setDirty(true);};
 const editScene=(key,value)=>{setManifest(m=>({...m,scenes:m.scenes.map((s,i)=>i===sceneIndex?{...s,[key]:value,...(key==='narration'?{audio_asset_id:null}:{})}:s)}));setDirty(true);};
 const save=async()=>{if(!dirty)return job;const b=await api('/jobs/'+job.id,'PUT',{manifest,revision:job.revision});setJob(b.job);setManifest(b.manifest);setPrepared(b.preview);setDirty(false);return b.job;};
 const queue=async(action,options={})=>{await save();const b=await api('/jobs/'+job.id+'/'+action,'POST',options);setJob(b.job);setNote('Masuk antrean. Worker akan memprosesnya.');await refresh();};
 const scene=manifest?.scenes[sceneIndex];
 const preview=manifest?{...manifest,music_url:manifest.music_asset_id?assets.find(a=>a.id===manifest.music_asset_id)?.url:null,scenes:manifest.scenes.map(s=>{const old=prepared?.scenes.find(x=>x.id===s.id);return {...s,asset_url:s.asset_id?assets.find(a=>a.id===s.asset_id)?.url:null,audio_url:s.audio_asset_id?assets.find(a=>a.id===s.audio_asset_id)?.url:null,captions:old?.audio_asset_id===s.audio_asset_id?old.captions:[],duration:old?.audio_asset_id===s.audio_asset_id?Math.max(s.duration,old.duration):s.duration};})}:null;
 const jump=i=>{setSceneIndex(i);player.current?.seekTo(preview.scenes.slice(0,i).reduce((n,s)=>n+Math.round(s.duration*30),0)+Math.min(20,Math.round(preview.scenes[i].duration*30)-1));};
 const move=delta=>{const to=sceneIndex+delta;if(to<0||to>=manifest.scenes.length)return;const copy=[...manifest.scenes];[copy[to],copy[sceneIndex]]=[copy[sceneIndex],copy[to]];edit('scenes',copy);setSceneIndex(to);};
 const upload=async(file,kind)=>{if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('tags',manifest?.title||'');const b=await api('/assets/upload','POST',fd);setAssets(a=>[b.asset,...a.filter(x=>x.id!==b.asset.id)]);if(kind==='music')edit('music_asset_id',b.asset.id);else editScene(kind==='audio'?'audio_asset_id':'asset_id',b.asset.id);setNote('Aset diunggah. Simpan perubahan untuk menggunakannya.');};
 let qa={};try{qa=JSON.parse(job?.qa_json||'{}');}catch{}
 return <div className="studio">
  <header className="studio-top"><a className="brand" href="/dashboard"><span className="brand-mark">G</span> GOLDGEN <span className="divider">/</span> <span>Motion Studio</span></a><div className="top-right"><span className={'connection '+(ready.ready_for_local_render?'ok':'')}>{ready.ready_for_local_render?'Renderer ready':'Renderer needs setup'}</span><a href="/dashboard">Dashboard ↗</a></div></header>
  <div className="studio-heading"><div><div className="eyebrow">THE FIELD JOURNAL</div><h1>Give your ideas motion.</h1><p>Build a visual story, one scene at a time.</p></div><div className="heading-actions">{manifest&&<><span className="revision">Revision {job.revision}{dirty?' · Unsaved':''}</span><button disabled={locked||!dirty} className="secondary" onClick={()=>act(async()=>{await save();setNote('Revisi tersimpan.');})}>Save changes</button><button disabled={locked||!ready.ready_for_local_render} onClick={()=>act(()=>queue('render'))}>Render video <span>↗</span></button></>}</div></div>
  {(error||note)&&<div role={error?'alert':'status'} className={'notice '+(error?'error':'')}>{error||note}<button className="plain" onClick={()=>{setError('');setNote('');}}>×</button></div>}
  <main className="workspace">
   <aside className="library panel"><div className="section-label">YOUR WORKSPACE</div><h2>Start a story</h2><label>Topic<input placeholder="Search your topic library…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Choose topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Choose a topic</option>{catalog.topics.filter(t=>t.headline.toLowerCase().includes(query.toLowerCase())).map(t=><option value={t.id} key={t.id}>{t.headline}</option>)}</select><button className="wide" disabled={busy||!topic||dirty} onClick={()=>act(async()=>{const b=await api('/jobs','POST',{topic_id:Number(topic)});await load(b.job.id);await refresh();})}>＋ Create storyboard</button><p className="hint">Starts with your existing facts. AI assistance is optional.</p>
    <div className="section-label space">RECENT PROJECTS</div><div className="project-list">{jobs.length===0&&<p className="hint">Your first story starts above.</p>}{jobs.map(j=><button disabled={busy||dirty} className={'project '+(job?.id===j.id?'selected':'')} key={j.id} onClick={()=>act(()=>load(j.id))}><strong>{j.topic_headline}</strong><span>{j.status} · revision {j.revision||1}</span></button>)}</div>
    <button className="secondary wide" disabled={busy} onClick={()=>act(async()=>{const r=await api('/assets/scan','POST',{});setAssets((await api('/assets')).assets);setNote(`${r.registered_count} gambar terdaftar.`);})}>Scan image library</button>
   </aside>
   <section className="canvas-panel panel"><div className="canvas-toolbar"><div><span className="section-label">LIVE COMPOSITION</span><h2>{manifest?.title||'A new perspective'}</h2></div><span className="format">9:16 · 30 FPS</span></div>
    <div className="preview-stage">{preview?<Player key={job.id} ref={player} initialFrame={20} component={Film} inputProps={{manifest:preview}} durationInFrames={durationFrames(preview)} compositionWidth={1080} compositionHeight={1920} fps={30} controls style={{width:'100%',maxWidth:305,aspectRatio:'9/16',boxShadow:'0 20px 55px #17251c22'}}/>:<div className="empty-poster"><div className="poster-kicker">GOLDGEN / MOTION NOTES</div><div className="poster-orbits"><i/><i/><i/><b>Au</b></div><h3>Small details.<br/>Remarkable stories.</h3><p>Choose a topic to begin.</p><div className="poster-footer">OBSERVE · TEST · COMPARE</div></div>}</div>
    {preview&&<><div className="preview-meta"><span>{(durationFrames(preview)/30).toFixed(1)} seconds · {preview.scenes.length} scenes</span><span>{preview.scenes.some(s=>s.audio_url)?'Narration attached':'Silent preview'}</span></div><div className="scene-strip">{manifest.scenes.map((s,i)=><button disabled={busy} className={'scene-card '+(i===sceneIndex?'selected':'')} key={s.id} onClick={()=>jump(i)}><span className="scene-number">{String(i+1).padStart(2,'0')}</span><strong>{s.title||names[s.component]}</strong><small>{names[s.component]} · {s.duration.toFixed(1)}s</small></button>)}<button className="add-scene" disabled={locked||manifest.scenes.length>=12} onClick={()=>{edit('scenes',[...manifest.scenes,{id:'scene-'+Date.now(),component:'annotated',title:'New scene',text:'',narration:'',duration:6,labels:[],motion:'push-in',transition:'fade',focal_x:50,focal_y:50,source_note:'',verified:false}]);setSceneIndex(manifest.scenes.length);}}>＋</button></div></>}
    {active&&<div className="job-progress"><strong>{job.action} · {job.progress_percent}%</strong><progress value={job.progress_percent} max="100"/><span>{job.current_detail}</span><button className="secondary" disabled={busy} onClick={()=>act(async()=>{await api('/jobs/'+job.id+'/cancel','POST',{});setNote('Pembatalan diminta.');})}>Cancel process</button></div>}
    {job?.error_message&&<div className="notice error">{job.error_message}</div>}
    {job?.render_revision&&<div className="exports"><div className="export-heading"><h3>Rendered version {job.render_revision}</h3><span>{job.render_revision!==job.revision||dirty?'Earlier revision':'Current revision'} · {job.elapsed_seconds?.toFixed(0)}s processing</span></div><div className="export-links">{[['video','MP4'],['subtitle','Subtitles'],['cover','Cover'],['contact','Contact sheet'],['caption','Caption'],['manifest','Manifest']].map(([kind,label])=><a key={kind} target="_blank" rel="noreferrer" href={`/api/motion/jobs/${job.id}/exports/${kind}`}>{label} ↗</a>)}<button className="secondary" onClick={()=>setReview(!review)}>{review?'Hide':'Review'} MP4</button></div>{review&&<video controls src={`/api/motion/jobs/${job.id}/preview`} style={{maxHeight:400,maxWidth:'100%'}}/>}{qa.warnings?.map(w=><p className="hint" key={w}>{w}</p>)}</div>}
   </section>
   <aside className="inspector panel">{scene?<><div className="section-label">SCENE {String(sceneIndex+1).padStart(2,'0')} / EDITOR</div><div className="inspector-title"><h2>Shape the story</h2><div><button className="plain" aria-label="Move scene earlier" disabled={locked||sceneIndex===0} onClick={()=>move(-1)}>←</button><button className="plain" aria-label="Move scene later" disabled={locked||sceneIndex===manifest.scenes.length-1} onClick={()=>move(1)}>→</button></div></div>
    <fieldset disabled={locked}><label>Scene type<select value={scene.component} onChange={e=>editScene('component',e.target.value)}>{catalog.components.map(c=><option key={c} value={c}>{names[c]}</option>)}</select></label><label>Cutaway model<select value={scene.diagram||'quartz-vein'} onChange={e=>editScene('diagram',e.target.value)}><option value="quartz-vein">Quartz vein</option><option value="river-bed">River sediment / bedrock</option></select></label><label>Headline<input maxLength={120} value={scene.title} onChange={e=>editScene('title',e.target.value)}/></label><label>On-screen text<textarea rows={3} maxLength={280} value={scene.text} onChange={e=>editScene('text',e.target.value)}/><small>{scene.text.length}/280</small></label><label>Labels · one per line<textarea rows={2} value={(scene.labels||[]).join('\n')} onChange={e=>editScene('labels',e.target.value.split('\n').slice(0,4))}/></label>
    <div className="two-fields"><label>Duration (s)<input type="number" min="1" max="45" step=".1" value={scene.duration} onChange={e=>editScene('duration',Number(e.target.value))}/></label><label>Motion<select value={scene.motion} onChange={e=>editScene('motion',e.target.value)}>{['push-in','glide','float','hold'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Transition<select value={scene.transition} onChange={e=>editScene('transition',e.target.value)}>{['fade','push','cut'].map(x=><option key={x}>{x}</option>)}</select></label>
    <details open><summary>Visual assets</summary><label>Scene image<select value={scene.asset_id||''} onChange={e=>editScene('asset_id',e.target.value||null)}><option value="">Procedural illustration</option>{assets.filter(a=>a.asset_type!=='audio').map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label><label className="upload">Upload image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>act(()=>upload(e.target.files[0],'image'))}/></label><div className="two-fields"><label>Focus X<input type="range" min="0" max="100" value={scene.focal_x} onChange={e=>editScene('focal_x',Number(e.target.value))}/></label><label>Focus Y<input type="range" min="0" max="100" value={scene.focal_y} onChange={e=>editScene('focal_y',Number(e.target.value))}/></label></div><button className="secondary wide" onClick={()=>act(async()=>{const j=await save();const b=await api('/jobs/'+j.id+'/match-assets','POST',{revision:j.revision,scene_id:scene.id});setManifest(b.manifest);setPrepared(b.preview);setJob(b.job);})}>Find matching internal image</button><button className="secondary wide" disabled={!ready.gemini_tts_key_present} onClick={()=>act(()=>queue('image',{scene_id:scene.id}))}>Generate illustration · AI</button><p className="hint">AI image generation uses your configured provider. Illustrations still need review.</p></details>
    <details open><summary>Narration & timing</summary><label>Spoken script<textarea rows={4} maxLength={1200} value={scene.narration} onChange={e=>editScene('narration',e.target.value)}/></label><div className="two-fields"><label>Voice<select value={voice} onChange={e=>setVoice(e.target.value)}>{['Kore','Puck','Charon','Fenrir','Aoede'].map(x=><option key={x}>{x}</option>)}</select></label><label>Audio<select value={scene.audio_asset_id||''} onChange={e=>editScene('audio_asset_id',e.target.value||null)}><option value="">No narration</option>{assets.filter(a=>a.asset_type==='audio').map(a=><option key={a.id} value={a.id}>{a.filename.slice(0,18)}</option>)}</select></label></div>{scene.audio_asset_id&&<audio controls src={assets.find(a=>a.id===scene.audio_asset_id)?.url} style={{width:'100%'}}/>}<button className="secondary wide" disabled={!ready.gemini_tts_key_present} onClick={()=>act(()=>queue('voiceover',{scene_id:scene.id,voice}))}>Generate scene voice · AI</button><label className="upload">Upload narration<input type="file" accept=".wav,.mp3,.m4a" onChange={e=>act(()=>upload(e.target.files[0],'audio'))}/></label><p className="hint">Scene timing expands to fit audio. Generated speech includes measured phrase captions. Uploaded audio needs caption alignment.</p></details>
    <details><summary>Sources & review</summary><label>Source / review notes<textarea rows={3} maxLength={1000} value={scene.source_note} onChange={e=>editScene('source_note',e.target.value)}/></label><label className="check"><input type="checkbox" checked={scene.verified} onChange={e=>editScene('verified',e.target.checked)}/> I reviewed this scene's claims</label></details>
    <details><summary>Project settings</summary><label>Visual style<select value={manifest.style} onChange={e=>edit('style',e.target.value)}>{catalog.styles.map(x=><option key={x}>{x}</option>)}</select></label><div className="two-fields"><label>Language<select value={manifest.language} onChange={e=>edit('language',e.target.value)}><option value="en">English</option><option value="id">Indonesia</option></select></label><label>Target seconds<input type="number" min="10" max="120" value={manifest.target_duration} onChange={e=>edit('target_duration',Number(e.target.value))}/></label></div><label>Background music<select value={manifest.music_asset_id||''} onChange={e=>edit('music_asset_id',e.target.value||null)}><option value="">No music</option>{assets.filter(a=>a.asset_type==='audio').map(a=><option key={a.id} value={a.id}>{a.filename.slice(0,18)}</option>)}</select></label><label className="upload">Upload licensed music<input type="file" accept=".wav,.mp3,.m4a" onChange={e=>act(()=>upload(e.target.files[0],'music'))}/></label><label>Export caption<textarea rows={4} value={manifest.caption} maxLength={2200} onChange={e=>edit('caption',e.target.value)}/></label><button className="secondary wide" disabled={!ready.gemini_tts_key_present} onClick={()=>act(()=>queue('voiceover',{voice}))}>Generate all voices · AI</button><button className="secondary wide" disabled={!ready.gemini_tts_key_present} onClick={()=>act(()=>queue('storyboard'))}>Create new storyboard revision · AI</button><p className="hint">Uses the current script as input. Previous revisions remain available. Provider charges apply; unchanged speech is cached.</p></details>
    <button className="danger wide" disabled={manifest.scenes.length<=1} onClick={()=>{edit('scenes',manifest.scenes.filter((_,i)=>i!==sceneIndex));setSceneIndex(Math.max(0,sceneIndex-1));}}>Remove scene</button></fieldset>
    <details><summary>Revision history</summary>{revisions.map(r=><button className="secondary wide" disabled={locked||dirty||r.revision===job.revision} key={r.revision} onClick={()=>act(async()=>{await api(`/jobs/${job.id}/restore/${r.revision}`,'POST',{});await load(job.id);})}>Restore revision {r.revision}</button>)}</details>
   </>:<div className="empty-inspector"><span>✦</span><h2>Every detail, intentional.</h2><p>Scene controls appear here when you open a storyboard.</p><ul><li>Eight visual compositions</li><li>Editable narration</li><li>Local video rendering</li></ul></div>}</aside>
  </main><footer className="studio-footer">GOLDGEN MOTION STUDIO <span>Composed with care. Rendered locally.</span></footer>
 </div>;
}
createRoot(document.getElementById('motion-root')).render(<App/>);
