#!/usr/bin/env python3
"""Test real posting to Facebook"""

import json
import requests
from pathlib import Path

# Load config
with open('data/config.json', 'r') as f:
    config = json.load(f)

# Get Erna Gold page (token is valid)
erna_page = None
for page in config['fanspages']:
    if page['name'] == 'Erna Gold':
        erna_page = page
        break

if not erna_page:
    print("❌ Erna Gold page not found")
    exit(1)

print("=" * 80)
print("🧪 TEST REAL POSTING TO FACEBOOK")
print("=" * 80)
print(f"\n📄 Target: {erna_page['name']}")
print(f"   Page ID: {erna_page['page_id']}")

# Find latest test image
import glob
images = glob.glob('generated_images/gold_poster_dryrun_*.png')
if not images:
    print("❌ No test image found")
    exit(1)

image_path = sorted(images)[-1]
print(f"   Image: {image_path}")

# Test caption
caption = """🚨 TEST POSTING - GoldGen Auto Poster 🚨

Halo! Ini adalah test posting otomatis dari sistem GoldGen Auto Poster.

✅ Caption: Generated by Gemini 3.1 Pro
✅ Image: Auto-generated poster
✅ Multi-fanspage: Supported

Sistem sedang dalam tahap testing. Mohon abaikan posting ini.

#TestPosting #GoldGen #AutoPoster"""

print(f"\n📝 Caption preview:")
print(caption[:150] + "...")

# Ask confirmation
response = input("\n⚠️  Posting ini akan BENAR-BENAR di-upload ke Facebook.\n   Lanjutkan? (yes/no): ")

if response.lower() != 'yes':
    print("\n❌ Posting dibatalkan")
    exit(0)

# Post to Facebook
print("\n🚀 Posting to Facebook...")
url = f"https://graph.facebook.com/v18.0/{erna_page['page_id']}/photos"

with open(image_path, 'rb') as image_file:
    files = {'source': image_file}
    data = {
        'message': caption,
        'access_token': erna_page['access_token']
    }
    
    response = requests.post(url, data=data, files=files)

if response.status_code == 200:
    result = response.json()
    post_id = result.get('id')
    print(f"\n✅ POSTING BERHASIL!")
    print(f"   Post ID: {post_id}")
    print(f"   URL: https://facebook.com/{post_id}")
else:
    print(f"\n❌ POSTING GAGAL!")
    print(f"   Status: {response.status_code}")
    print(f"   Error: {response.text}")

print("\n" + "=" * 80)
