"""Source-guided editorial briefs for the Hidden Gold series."""

LAYOUT = 'DEEP CUTAWAY EXPLAINER'
LAYOUT_DEFINITION = {
    'name': LAYOUT,
    'topic_series': ['Hidden Gold: Beneath the Surface'],
    'composition': 'Reference-inspired educational reveal in vertical 9:16. For geological profiles, reserve about 20 percent at the top for the surface landscape and use the rest for a large realistic cutaway. Connect 2-3 circular detail insets to their actual locations with thin leader lines. For material journeys, use a connected source-to-valley section. For microscopic topics, replace the landscape with one large specimen and magnified insets; never invent soil layers. Warm earth tones, realistic textures, restrained metallic gold highlights, strong contrast and generous space for the existing short-label budget. Depict only the topic\'s specific mechanism, not a treasure-filled pit.',
}
GOLD = 'https://pubs.usgs.gov/gip/prospect1/goldgip.html'
CHANNELS = 'https://pubs.usgs.gov/wsp/0314/report.pdf'
VEINS = 'https://pubs.usgs.gov/bul/b1693/html/bull8x2r.htm'
FALSE_BEDROCK = 'https://pubs.usgs.gov/mf/0880-B/plate-2.pdf'
MICROBES = 'https://digital.library.adelaide.edu.au/items/775a84e1-7925-4b3b-991e-d39abea04558'

# Stable keys and reserved IDs survive persistent-volume catalog projection.
# Each brief describes a conceptual illustration, never a surveyed location.
BRIEFS = [
    ('river-bend', 'BENEATH THE RIVER BEND', 'river', 'cutaway', GOLD,
     'Reveal gravel and bedrock beneath a river bend.',
     'Show a bend with water above a gravel cross-section and irregular bedrock below.',
     'Explain that local flow, sediment supply and bed geometry affect deposition; an inside bend is not guaranteed paydirt.'),
    ('bedrock-crack', 'INSIDE A BEDROCK CRACK', 'river', 'cutaway', GOLD,
     'Look inside one possible natural sediment trap.',
     'Zoom from a riverbed into a narrow crack containing packed sediment and a few illustrative heavy grains.',
     'Explain possible physical trapping without implying every crack contains gold.'),
    ('boulder', 'BEHIND THE BOULDER', 'river', 'cutaway', GOLD,
     'See how an obstacle changes the surrounding sediment pattern.',
     'Show water moving around a boulder and a cutaway of adjacent gravel pockets.',
     'Treat deposition and scour as locally variable; do not mark one side as a certain gold location.'),
    ('waterfall', 'UNDER THE WATERFALL POOL', 'river', 'cutaway', GOLD,
     'Reveal the shape of a pool floor beneath moving water.',
     'Show a conceptual bedrock depression with sediment pockets and a zoom of mixed gravel.',
     'Discuss possible sediment retention and removal, not guaranteed gold; do not depict entering turbulent water or underwater excavation.'),
    ('buried-river', 'THE RIVER BENEATH THE HILLSIDE', 'ancient-river', 'cutaway', CHANNELS,
     'Explore an illustrative old channel hidden by younger material.',
     'Show buried channel-shaped gravel beneath a hillside and distinguish it from surrounding rock.',
     'Explain that an ancient channel requires geological evidence; a hillside alone cannot reveal its presence or grade.'),
    ('river-terrace', 'WHEN THE RIVER RAN HIGHER', 'ancient-river', 'cutaway', CHANNELS,
     'Connect a hillside terrace with an earlier river level.',
     'Show terrace gravel above the present channel with an inset of the gravel contact.',
     'Explain preservation of older deposits without assuming every terrace is gold-bearing.'),
    ('dry-wash', 'BENEATH A DRY WASH', 'ancient-river', 'cutaway', GOLD,
     'A dry surface can cover deposits left by earlier flows.',
     'Show a dry desert channel over several contrasting sediment lenses and uneven bedrock.',
     'Explain episodic sediment transport without imposing a universal layer sequence or gold depth.'),
    ('old-channel', 'OLD CHANNEL, NEW RIVER', 'ancient-river', 'cutaway', CHANNELS,
     'Compare a former channel with the present river.',
     'Show an offset buried gravel channel beside a modern river in one valley cross-section.',
     'Distinguish a conceptual reconstruction from a mapped discovery; neither channel guarantees gold.'),
    ('vein-valley', 'FROM VEIN TO VALLEY', 'gold-source', 'journey', GOLD,
     'Follow material from a mineralized source toward a valley.',
     'Connect a weathering vein, slope debris and stream gravel with a few directional arrows.',
     'Explain release, transport and possible concentration as separate processes, without a fixed distance or timescale.'),
    ('weathered-vein', 'INSIDE A WEATHERED QUARTZ VEIN', 'gold-source', 'cutaway', VEINS,
     'Compare intact rock with a weathered portion of a vein.',
     'Show fractured quartz in host rock, loose fragments and an inset of the weathered contact.',
     'Quartz can occur without gold; show only sparse illustrative gold where the scenario explicitly assumes mineralization.'),
    ('outcrop', 'WHAT LIES BELOW THE OUTCROP?', 'gold-source', 'cutaway', VEINS,
     'A surface exposure is only part of a geological structure.',
     'Show an exposed vein with a visibly schematic possible continuation below the surface.',
     'State that depth, continuity and gold content cannot be determined from surface appearance alone.'),
    ('near-source', 'GOLD NEAR ITS SOURCE', 'gold-source', 'journey', GOLD,
     'Compare material near a source with material moved downslope.',
     'Show weathered source rock, nearby debris and transported sediment as connected zones.',
     'Do not infer an exact source distance from grain shape or confuse residual material with all transported deposits.'),
    ('false-bedrock', 'FALSE BEDROCK EXPLAINED', 'hidden-layers', 'cutaway', FALSE_BEDROCK,
     'A resistant sediment layer is not always the underlying bedrock.',
     'Show a resistant layer within sediment above a separate true bedrock surface.',
     'Explain false bedrock as a possible trapping horizon; neither resistant layers nor deeper bedrock guarantee gold.'),
    ('black-sand', 'BLACK SAND BENEATH THE SURFACE', 'hidden-layers', 'cutaway', GOLD,
     'Inspect a dark band of mixed heavy minerals.',
     'Show a dark sediment lens with a circular enlargement of different mineral grains.',
     'Black sand is not proof of gold; avoid identifying every dark grain as magnetite.'),
    ('rust-ground', 'BENEATH THE RUST-COLORED GROUND', 'hidden-layers', 'cutaway', VEINS,
     'Investigate weathering beneath an iron-stained surface.',
     'Show rusty fractures and contrasting weathered and less-weathered rock in a conceptual profile.',
     'Iron staining alone does not establish gold mineralization; do not draw a guaranteed gold seam under red soil.'),
    ('gravel-layers', 'ONE GRAVEL BED, DIFFERENT LAYERS', 'hidden-layers', 'cutaway', GOLD,
     'Look at variation within a single sediment deposit.',
     'Show irregular sand and gravel lenses with different grain sizes rather than perfectly uniform stripes.',
     'Explain differing depositional conditions; compare layers without inventing assays or a richest depth.'),
    ('tailings', 'INSIDE AN OLD TAILINGS PILE', 'historic-mining', 'cutaway', GOLD,
     'Reveal the mixed material left by earlier processing.',
     'Show a conceptual pile of processed gravel with variable internal lenses and a grain-detail inset.',
     'Do not assume historical equipment missed recoverable gold or encourage disturbing potentially contaminated waste.'),
    ('old-workings', 'WHAT OLD WORKINGS REVEAL', 'historic-mining', 'cutaway', VEINS,
     'Read historical workings as clues that require context.',
     'Show a schematic surface working beside a vein exposure, with no people entering openings.',
     'Historical excavation does not prove remaining reserves; distinguish documented evidence from reconstruction.'),
    ('mining-landscape', 'BENEATH A HISTORIC MINING LANDSCAPE', 'historic-mining', 'cutaway', CHANNELS,
     'Connect surface traces with an illustrative geological section.',
     'Show old surface workings, sediment and underlying rock in a conceptual landscape cutaway.',
     'Do not invent a named mine, mapped tunnel network or hidden treasure; do not portray entry into abandoned workings.'),
    ('gold-grain', 'INSIDE A GOLD GRAIN', 'microscopic', 'micro', MICROBES,
     'Explore textures that a normal field photograph cannot resolve.',
     'Use one enlarged gold grain as the main object with insets of pores and surface texture.',
     'Present a conceptual scientific illustration, not a laboratory image or evidence of the origin of a particular specimen.'),
    ('tiny-gold', 'GOLD TOO SMALL TO SEE', 'microscopic', 'micro', GOLD,
     'Gold can occur at scales beyond unaided vision.',
     'Zoom from a rock sample to schematic tiny inclusions; make the enlargement visually explicit.',
     'Do not imply invisible gold is present in any ordinary rock or can be confirmed by a photograph; avoid invented scale bars.'),
    ('microbes', 'CAN MICROBES CHANGE GOLD?', 'microscopic', 'micro', MICROBES,
     'Explore microbial contributions to changes on gold surfaces.',
     'Show one gold grain with schematic surface microbes and a close-up of small secondary particles.',
     'Describe studied dissolution and re-precipitation processes; do not imply rapid nugget growth, universal microbial layers or thermophilic conditions without evidence.'),
]

ADDITIONS = [
    {
        'id': 11001 + index,
        'curation_key': 'hidden-gold-' + key,
        'headline': title,
        'subtitle': subtitle,
        'editorial_angle': subtitle,
        'series': 'Hidden Gold: Beneath the Surface',
        'topic_family': family,
        'visual_mode': mode,
        'allowed_layouts': [LAYOUT],
        'list_header': 'BENEATH THE SURFACE',
        'list_points': [scene, explanation,
                        'Use a conceptual illustration, not a surveyed site or a prediction of gold presence.',
                        'Do not invent fixed depths, grades, yields, time scales or abundant nuggets throughout the scene.'],
        'reference_url': source,
    }
    for index, (key, title, family, mode, source, subtitle, scene, explanation) in enumerate(BRIEFS)
]
